
services:
  tekton-webapi:
    image: angelbus/tekton-webapi:1.0.0
    container_name: tekton-webapi
    networks:
      - angelbustamante
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=https://+:5100;http://+:5010
      - ASPNETCORE_HTTPS_PORT=5100
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
      - DatabaseSettings__ConnectionString=Server=postgres;Port=5433;Database=fshDb;User Id=postgres;Password=admin
      - HangfireSettings__Storage__ConnectionString=Server=postgres;Port=5433;Database=fshDb;User Id= postgres;Password=admin
      - DatabaseSettings__DBProvider=postgresql
      - HangfireSettings__Storage__StorageProvider=postgresql
      - ElasticSearchUrl=http://localhost:9200/
      - ExternalDiscountsUrl=https://6603b4cb2393662c31cf74e8.mockapi.io/
      - DiscountsRequestUrl=products/
      - CacheExpirationMinutes=5
    volumes:
      - ~/.aspnet/https:/https:ro
      - ./Logs:/App/Logs
    ports:
      - 5100:5100
      - 5010:5010
    depends_on:
      - postgres
    restart: on-failure
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    networks:
      - angelbustamante
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - PGPORT=5433
    ports:
      - 5433:5433
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
  # elk:
  #     container_name:  elasticsearch-kibana
  #     image: sebp/elk:oss-8.5.3
  #     environment:
  #       - LOGSTASH_START=0
  #     volumes:
  #       - sebp-elk-data:/usr/share/elk/data
  #     ports:
  #       - 5601:5601
  #       - 9200:9200
  #     networks:
  #       - angelbustamante
volumes:
  postgres-data:
  # sebp-elk-data:
networks:
  angelbustamante:
    name:  angelbustamante